### ISSUE TITLE
Fix Connection Form and Contact us form - Mobile

### ISSUE THREAD

**Issue by t-rhex** [t-rhex/OpenSourceChurchTemplate#7]
**Describe the bug**
Connection form and contact us form for mobile devices. The form is not in full view and is also unscrollable. Double-check the MODAL 

**To Reproduce**
1. Open Chrome Developer Tool
2. Switch to Mobile Devices such as iPhone 12
3. Click on Connection Form and Contact Form.

**Expected behavior**
The modal should be in full view and we should be able to see the Close button at the top also should be scrollable, so the user can submit the form.

**Screenshots**
![image](https://github.com/user-attachments/assets/5aaf4eb4-5ed1-4044-a8dd-e17bdcef8a68)

**Additional context**
N/A

**Acceptance Criteria**
Thorough testing and screenshots. Review Mobile and Web.

**Comment by Wasid786** [comment]
Hello @t-rhex,
I would like to solve this issue. Can you assign me this issue?

**Comment by t-rhex** [comment]
@Wasid786  Hello ! I have assigned this issue to you. Feel free to make changes and create a Pull request. Appreciate your contribution. Please note that I am still working on setting up this repository. If you see any issues, please feel free to comment on this thread or reach out to me through discord https://discord.gg/Q2RcDDq3. Features/Improvements ideas are welcome.
