### ISSUE TITLE
Hyperlink address

### ISSUE THREAD

**Issue by t-rhex** [t-rhex/OpenSourceChurchTemplate#8]
**Describe the bug**

Some links are not working

1. https://revival-tan.vercel.app/location 
2. Learn more link not working - https://revival-tan.vercel.app/about/aboutus
3. Get Involved all links broken - https://revival-tan.vercel.app/getinvolved
4. Fix the GIVE NOW link - https://revival-tan.vercel.app/give
5. Digital Payment option QR code missing - Broken images

**To Reproduce**
1. Iterate over each link and review. This issue is expected on both Web and Mobile.

**Expected behavior**
1. Link should work properly

**Additional context**

### Acceptance Criteria

Thorough testing and screenshots. Review Mobile and Web.

**Comment by Maduz0097** [comment]
Can you please assign this issue to me? I want to help and I have already fixed the issue. Thank you!

**Comment by t-rhex** [comment]
@Maduz0097 Hello ! I have assigned this issue to you. Feel free to make changes and create a Pull request. Appreciate your contribution. Please note that I am still working on setting up this repository. If you see any issues, please feel free to comment on this thread or reach out to me through discord https://discord.gg/Q2RcDDq3. Features/Improvements ideas are welcome.
